/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as randomNumberlotterySepoliaSol from "./RandomNumberlottery_sepolia.sol";
export type { randomNumberlotterySepoliaSol };
import type * as vrFv2ConsumerSol from "./VRFv2Consumer.sol";
export type { vrFv2ConsumerSol };
import type * as myNftSol from "./myNft.sol";
export type { myNftSol };
export type { RandomNumberlottery } from "./RandomNumberlottery";
