/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as randomNumberlotterySepoliaSol from "./RandomNumberlottery_sepolia.sol";
export type { randomNumberlotterySepoliaSol };
import type * as vrFv2ConsumerSol from "./VRFv2Consumer.sol";
export type { vrFv2ConsumerSol };
import type * as myErc20Sol from "./myErc20.sol";
export type { myErc20Sol };
import type * as myNftSol from "./myNft.sol";
export type { myNftSol };
import type * as tradingSwapSol from "./trading_swap.sol";
export type { tradingSwapSol };
export type { RandomNumberlottery } from "./RandomNumberlottery";
