/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as vrFv2ConsumerSol from "./VRFv2Consumer.sol";
export type { vrFv2ConsumerSol };
import type * as myNftSol from "./myNft.sol";
export type { myNftSol };
export type { RandomNumberDirectFundingConsumerV2 } from "./RandomNumberDirectFundingConsumerV2";
export type { RandomNumberlottery } from "./RandomNumberlottery";
