/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { RandomNumberlottery__factory } from "./RandomNumberlottery__factory";
export { RandomNumberlottery_s__factory } from "./RandomNumberlottery_s__factory";
