/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RandomNumberlottery } from "./RandomNumberlottery";
export type { RandomNumberlottery_s } from "./RandomNumberlottery_s";
